---
- name: TEST EDA
  hosts: "{{ device | default('all') }}"
  gather_facts: false

  tasks:
  - name: Set stats
    ansible.builtin.set_stats:
        aggregate: false
        data:
          downinterface: "{{ downinterface }}"

  - name: Enable {{ downinterface }}
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ downinterface }}"
          enabled: true
