---
- name: Remediate Downed Interface
  hosts: "{{ device | default('all') }}"
  gather_facts: false

  tasks:
  - name: Enable Interface
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ if_name }}"
          enabled: true
