---
- name: TEST EDA
  hosts: "{{ device | default('all') }}"
  gather_facts: false

  tasks:
  - name: Enable {{ downinterface }}
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ downinterface }}"
          enabled: true
