---
- name: TEST EDA
  hosts: all
  gather_facts: false
  vars:
    organization: vem

  tasks:
  - name: Enable {{ port }}
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ port }}"
          enabled: true
