---
- name: Demo rules with kafka as source
  hosts: all
  sources:
  - ansible.eda.kafka:
      topic: telegraf
      host: 10.255.4.221
      port: 9092
      group_id:
  rules:
    - name: A Down Interface has been detected
      condition: event.body.fields.new_state == "interface-notif-state-down"
      action:
        run_job_template:
          name: enable_port.yml
          organization: vem
          job_args:
            extra_vars:
              if_name: "{{ event.body.fields.if_name }}"
              device: "{{ event.body.fields.host_name }}"